### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [GrammaTech/cl-capstone#1]
Building with SBCL 2.2.1.147-31b6a20e3 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id c3930bb340a12d38b7d4279327c147c3a97c7ea8

*capstone* fails to build with the following error:

```
; caught WARNING:
;   Derived type of CAPSTONE::L is (VALUES SB-SYS:SYSTEM-AREA-POINTER &OPTIONAL), conflicting with its asserted type SEQUENCE.
;   See also:
;     The SBCL Manual, Node "Handling of Types"
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BD0003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "capstone" "capstone">

```

*capstone/test* fails to build because of a failure in  _capstone_.

[Full log here](http://report.quicklisp.org/2022-03-22/failure-report/cl-capstone.html)

**Comment by jaruchti** [comment]
Hey Zach, thanks for the heads up : ). I am discussing internally as possible patch and will post when complete.

**Comment by jaruchti** [comment]
Okay, I think this should be good-to-go now that the most recent commit has been reverted.
